### PR TITLE
PDP10, PDP11, Unibus VAX: Set CH11 TX done on reset.

### LINKED ISSUE #637: CH11 problems
I'm testing the CH11 device with the MINITS software for PDP-11.  It's a Chaosnet router, terminal concentrator, and general purpose network utility.

It doesn't work yet.  There are three problems:

1. TX done must be set when the device is reset.  Easily fixed.
2. `sim_clock_coschedule` doesn't trigger any calls to `ch_svc`.  I have temporarily replaced those with `sim_activate`, but of course fixing the root cause is desirable.
3. TMXR doesn't appear to see any incoming packets.  That's strange, because the same CH11 code works with vax780 running 4.1BSD.  I do see incoming packets with `tcpdump`.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Fixes #637.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Tested with:
- vax780 running 4.1BSD.
- pdp11 running MINITS.

**Comment by markpizz** [comment]
Hmm...  You didn't pull before you committed this and thus missed some SCP related commits.

**Comment by larsbrinkhoff** [comment]
Rebased, and rechecked.

**Comment by markpizz** [comment]
Merged.

Please pull from master again now before making other changes.  I made a couple of minor changes to pdp11_ch.c. 
1) Fixing SHOW CH before NODE and PEER have been set
2) Adding TMXR level debug options.

**Pull request merged**
