### PR TITLE
ALTAIRZ80: Add JADEDD Jade Double D disk controller device

### PR DESCRIPTION
**Pull request by deltecent**
This PR adds a JADE Double D disk controller `JADEDD` device to the AltairZ80 simulator.

### CODE REVIEW

**Comment by markpizz** [comment]
@deltecent, 
1) Please remove the tabs in s100_jadedd.c
2) Please add the changed files in this zip [jadedd.zip](https://github.com/simh/simh/files/4671594/jadedd.zip) to your revised commit (located in the directories that they're already found).

@psco this is OK, right?

@deltecent If @psco is OK with this, please submit a new pull request with these things fixed.

**Comment by psco** [comment]
Yes, this is OK. Please proceed.

**Comment by markpizz** [comment]
By the way, also, please fix:

**Comment by markpizz** [comment]
1>..\AltairZ80\s100_jadedd.c(536) : warning C4101: 'sio_uptr' : unreferenced local variable
1>..\AltairZ80\s100_jadedd.c(535) : warning C4101: 'sio_dptr' : unreferenced local variable

**Pull request closed without merging**
