### PR TITLE
Travis matrix build.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Split the monolithic Travis CI "make all" build into several jobs, one for each simulator.

### CODE REVIEW

**Comment by markpizz** [comment]
Are these 'jobs' done sequentially, or in parallel?  If is done in parallel, then is there some way to have a separate job that is done first before the parallel jobs start.  Specifically, a job that does 'make BIN/buildtools/BuildROMs' is needed.  Otherwise, parallel jobs will race each other (and possibly clobber something) running this internal step.

**Comment by larsbrinkhoff** [comment]
I believe they are done in parallel, subject to a limited number of virtual machines.

I also believe each job is done in a separate virtual machine, so they don't clobber each other.

**Comment by larsbrinkhoff** [comment]
Well, all jobs finished.  Individual jobs are 1-7 minutes (16 for one outlier), but the accumulated time is over eight hours.  This is mostly because of the slow mac machines.

**Comment by markpizz** [comment]
I feel guilty about the resources expended as a consequence of what might be a rather minor commit which often doesn't affect the code (and thus the build outcome).  For example: c1d9db8be7e47b31f

**Comment by larsbrinkhoff** [comment]
That may be a concern.  Sometimes I wish there were a more selective approach to building commits, but it's all or nothing.

Maybe things will be different if a few simulators are bundled together in a job?  Let's try that and see what happens.

**Comment by markpizz** [comment]
I'd say to go for 10 at a time.  Once this is stabilized, I'll change the make logic and the VAX test script to skip testing after more than 3 VAX simulators have run tests in a single make execution.

**Comment by larsbrinkhoff** [comment]
I had each job build around seven simulators, and the build time was reduced to two hours.

I'll update it to do 10.

**Comment by larsbrinkhoff** [comment]
With builds batched 10 to the job, the accumulated build time is around 1.5 hours.

**Comment by markpizz** [comment]
Before making this the method, I'm wondering if/how well/how fast a "make -j" would execute and if it would correctly catch build errors.

**Comment by markpizz** [comment]
Or maybe some limited -j like "-j 4" would be more reasonable...

**Comment by markpizz** [comment]
or more clearly "--jobs=4"

**Comment by markpizz** [comment]
I see you've got travis jobs with 10 simulators each and a make --jobs=4 going in each.  What I actually meant, was to see if, with one travis job, --jobs=4 runs quickly enough to avoid the extra travis overhead of setting up each new VM for the job and the configuration setup for each...

Also, for the sake of testing, try putting in some garbage at the beginning of one of the source modules (say PDP10) and see if the single travis job reports an error if the make has "--jobs=4" on it...

**Comment by larsbrinkhoff** [comment]
Done.

Note: 98f1b80 failed because Travis stops a job if a new commit is made to the same branch.

**Comment by markpizz** [comment]
From this message: "No output has been received in the last 10m0s, this potentially indicates a stalled "

It seems that --jobs=n isn't the right path to take.  I suspect that each VM is only given a single CPU so parallel compiles will just be thrashing.  Meanwhile the lack of continuous output during the thrashing (as indicated above) gets Travis confused anyway.

So, I think the separate jobs doing maybe 15 compiles each will be reliable.

**Comment by markpizz** [comment]
Merged a while back by Cherry pick.

**Pull request closed without merging**
