### PR TITLE
AltairZ80: Add MDS-AD support for single-density

### PR DESCRIPTION
**Pull request by hharte**
The North Star MDS-AD disk controller supports both single- and
double-density operation.  While mixed-density is supported by the
controller, it is not supported by AltairZ80 due to a limitation of the
.nsi image file format.  The .nsi image file format requires all sectors
to be of the same density.

### CODE REVIEW

**Comment by hharte** [comment]
FYI, @psco

**Comment by psco** [comment]
Thanks Howard!

**Comment by markpizz** [comment]
@psco, does Thanks mean you're OK with this?

**Comment by psco** [comment]
Yes, this PR is fine.

**Pull request merged**
