### PR TITLE
Update alpha_sys.c

### PR DESCRIPTION
**Pull request by irsbugs**
Correct typos in 4 x mnemonics in _const char *opcode[]_. Remove 7 x extra space characters in _const uint32 opval[]_.

Four corrections to typos in mnemonics in _const char *opcode[]_ in alpha_sys.c:
_L should be _C for opcodes 2E and 2F. 

Alpha simulator V4.0-0 Current        git commit id: 3c1c92dc
sim> ; Opcode 2E
sim> ev -m 0xB8000000
0:	STL_L R0,0(R0)
4:	00000000B8000000
sim> 
sim> ; Opcode 2F
sim> ev -m 0xBC000000
0:	STQ_L R0,0(R0)
4:	00000000BC000000
sim> 

According to, Alpha Architecture Handbook V4, October 1998, Table C2:
There are no instructions with the mnemonics STL_L or STQ_L, but there are STL_C and STQ_C.

The nmemonics are correct in https://github.com/simh/simh/blob/master/alpha/alpha_cpu.c
    case OP_STL_C:                                      /* STL_C */
    case OP_STQ_C:                                      /* STQ_C */

but in https://github.com/simh/simh/blob/master/alpha/alpha_sys.c  
In const char *opcode[] = { the line:

 "STL", "STQ", "STL_L", "STQ_L",
 
has been corrected to be:
 
 "STL", "STQ", "STL_C", "STQ_C", 

=====

BF should be FB in mnemonic for Opcode 36.

Alpha simulator V4.0-0 Current        git commit id: 3c1c92dc
sim> ; Opcode 36
sim> ev -m 0xD8000000
0:	BFGE R0,4
4:	00000000D8000000
sim> 

According to, Alpha Architecture Handbook V4, October 1998, Table C2:

FBGE Bra 36 Floating branch if ≥ zero

This is correct in https://github.com/simh/simh/blob/master/alpha/alpha_cpu.c
    case OP_FBGT:                                       /* FBGT */
    
but in https://github.com/simh/simh/blob/master/alpha/alpha_sys.c    
In const char *opcode[] = { the line

 "BSR", "FBNE", "BFGE", "FBGT",
 
 has been corrected to be...

 "BSR", "FBNE", "FBGE", "FBGT", 

=====

MULLQ/V should MULQ/V as the mnemonic for Opcode 13.60

sim> ; Opcode 13.60
sim> ev -m 0x4C000C00
0:	MULLQ/V R0,R0,R0
4:	000000004C000C00
sim> 

According to, Alpha Architecture Handbook V4, October 1998, Table C2:

MULQ/V Opr 13.60 Multiply quadword 

This is correct in https://github.com/simh/simh/blob/master/alpha/alpha_cpu.c
        case 0x60:                                      /* MULQ/V */
 
but in https://github.com/simh/simh/blob/master/alpha/alpha_sys.c    
In const char *opcode[] = { the line
 
 "MULL/V", "MULLQ/V", 
 
has been corrected to be:

 "MULL/V", "MULQ/V",

======

In alpha.sys.c the _const uint32 opval[]_ had seven cases of double space characters. These extra space characters have been removed.

### CODE REVIEW

**Comment by markpizz** [comment]
Hi @irsbugs,

2 things:

1) Can I get your full name?
2) The changes are simple and seem perfectly reasonable.  I'd prefer that the commit message have a header that said:

alpha: Correct opcode mnemonics
\<skip-a-line\>
Then essentially the complete text you provided in this pull request as the rest of the commit message skipping the first line that summarizes the effect of the diff: "Correct typos in 4 x mnemonics in const char *opcode[]. Remove 7 x extra space characters in const uint32 opval[].".

You can do this by backing out the prior commit and doing a push -f to your github repo, or I'll do it via cherry pick once I get your full name.  

Thanks.

- Mark

**Comment by irsbugs** [comment]
Hi Mark,

>     Can I get your full name?

Ian Robert Stewart

> You can do this by backing out the prior commit and doing a push -f to your github repo, or I'll do it via cherry pick once I get your full name.

I'd prefer that you do it via cherry pick as I am not very experienced with using github.

Regards, Ian.

**Comment by markpizz** [comment]
No problem.  Just wondering, how did you manage to find this stuff?  What inspired you?

**Comment by irsbugs** [comment]
Hi Mark,

> how did you manage to find this stuff?

A friend in our local Linux Users Group told me about simh.


> What inspired you?

I used to work for DEC. As part of servicing the PDP11 computers it was necessary to write small programs in machine code. However, at the time, my code only used looping on CSR's, rather than using device interrupts. So last year I experimented with the simh/pdp11. I wrote a program called 'stop-watch' that uses device interrupts for the KW11 and the console. It is posted on my github repository... https://github.com/irsbugs/pdp11-code

In the 1990's I was too busy working to find the time to learn the Alpha instruction set. So this year I compiled the simh/alpha code to experiment with writing Alpha machine code. I'm part way through writing a Python/GTK GUI application that will show how Alpha instructions are constructed. The 32 bits of each instruction are displayed and manipulation of the instructions registers and displacements, etc. are performed via slide and spin control widgets. Once an instruction is constructed my program passes its hex code to simh/alpha to retrieve the mnemonic.

On launching my Python program it reads the simh/alpha alpha_sys.c file to get the lists of mnemonics and the hex of the instructions. So, that explains how I spotted some typo's in the files 'const char *opcode[]' and 'const uint32 opval[]' data.

When I get my 'Alpha Instruction Builder' program operational I post it on my github repository.

cheers, Ian.

**Comment by markpizz** [comment]
Hi Ian,

> > how did you manage to find this stuff?
> 
> A friend in our local Linux Users Group told me about simh.
> 
> > What inspired you?
> 
> I used to work for DEC. As part of servicing the PDP11 computers it was necessary to write small programs in machine code. However, at the time, my code only used looping on CSR's, rather than using device interrupts. So last year I experimented with the simh/pdp11. I wrote a program called 'stop-watch' that uses device interrupts for the KW11 and the console. It is posted on my github repository... https://github.com/irsbugs/pdp11-code
> 
> In the 1990's I was too busy working to find the time to learn the Alpha instruction set. So this year I compiled the simh/alpha code to experiment with writing Alpha machine code. I'm part way through writing a Python/GTK GUI application that will show how Alpha instructions are constructed. The 32 bits of each instruction are displayed and manipulation of the instructions registers and displacements, etc. are performed via slide and spin control widgets. Once an instruction is constructed my program passes its hex code to simh/alpha to retrieve the mnemonic.
> 
> On launching my Python program it reads the simh/alpha alpha_sys.c file to get the lists of mnemonics and the hex of the instructions. So, that explains how I spotted some typo's in the files 'const char *opcode[]' and 'const uint32 opval[]' data.
> 
> When I get my 'Alpha Instruction Builder' program operational I post it on my github repository.

That's a good story. :-)

Your changes have been merged via Cherry Pick crediting you as author.

- Mark

**Pull request closed without merging**
