### PR TITLE
Add CI email notifications.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Email messages should be sent to @markpizz when Travis CI builds fail, or are fixed, etc.

See this for details:  
https://docs.travis-ci.com/user/notifications

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm adding myself too.

The default behaviour is to always send a message when a build fails, and also when a failing build has been fixed.

**Comment by larsbrinkhoff** [comment]
I'll let this hang around in draft state for a while so I can test failing builds.

**Comment by larsbrinkhoff** [comment]
I think this should work.

**Comment by markpizz** [comment]
Merged with Cherry Pick, slight rephrased commit message, attribute Lars as author

**Pull request closed without merging**
