### PR TITLE
AltairZ80: set sim_clock_precalibrate_commands and sim_vm_initial_ips

### PR DESCRIPTION
**Pull request by deltecent**
For @markpizz and @psco to consider.

### CODE REVIEW

**Comment by psco** [comment]
This should be rejected as the "reasonable" instruction mix is in fact a busy wait loop on an uninitialised disk device.

**Comment by deltecent** [comment]
My understanding is the instruction mix isn't really supposed to do anything useful. It is to be 3-4 instructions that exercise various paths through the VM to give SIMH a general starting point for timing. If there is a problem banging on port 8, then we can probably use FF.

>The simulator framework provides a means of pre-calibrating the instruction execution rate.  A sequence of three to four instructions that run in a tight loop can be used at simulator startup time to compute the execution rate.

**Comment by markpizz** [comment]
The goal of the pre-calibrate exercise is to come up with a reasonable approximation of a  somewhat "normal" instruction mix that actually runs at a similar rate to how real instructions do when the simulator is doing something useful. 

I can't personally tell if the results, in this case, are true.  However, other simulators tend to get much faster instruction rates when the mix they test with doesn't include some percentage of non computational (i.e. instructions which reference some aspect of other pieces of the simulator which support I/O activities).  

Much faster pre-calibration is not better.

**Comment by psco** [comment]
One problem is that if you do I/O (i.e. IN or OUT instructions, any port btw.) you are invoking parts of the simulator which are for all we know in basically an undefined state. The other problem is that having one out of four instructions an I/O instruction is hardly what is a "reasonable approximation of a somewhat "normal" instruction mix".

**Comment by deltecent** [comment]
@psco it is probably best that you come up with an instruction mix, assuming you want to add pre-calibration to AltairZ80.

**Comment by markpizz** [comment]
The goal is to get  a number which is similar to the numbers observed when doing something useful.  Surely the device(s) may be in an indeterminate state, but that state will be the same each time the simulator is started so some consistent behaviors/timings can be measured.

**Comment by psco** [comment]
Honestly I am not keen at all to add yet another piece of timer related complexity with unclear benefit and a high potential of more trouble down the road. Furthermore I see only few simulators implementing this which is not encouraging either.

**Comment by deltecent** [comment]
As I may be the only person that uses AltairZ80 in a way where timing is important, that course of action seems reasonable. I'll maintain the timing changes in my own fork. What I learned through this process is that the internal workings of the timer functions are mystical voodoo magic, but they seem to work when used appropriately.

**Pull request closed without merging**
