### PR TITLE
CI: Build using GitHub Actions.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Continuous integration build using GitHub Actions.  See https://github.com/features/actions

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Here's what it should look like after the branch has been merged:  
https://github.com/larsbrinkhoff/simh/actions

**Comment by markpizz** [comment]
For the uninformed (me), please explain the net result of this.  What is the logical change?  Will Travis go away?  Will the osx builds be less likely to fail for "environmental" reasons rather than actual issues in the simh codebase?

**Comment by larsbrinkhoff** [comment]
I have only been testing this for a few hours, so I don't know if the GitHub Actions will be more stable than Travis CI.  The the builds seem good so far, though.  Certainly much faster.

Rumor has it that Travis CI will reduce their service: https://twitter.com/james_hilliard/status/1336081776691843072
I think I have seen jobs staying queued up for longer lately.

So at this point, the net result is a redundant second source of CI builds.  In the future, it could be an exit path away from Travis CI.

**Comment by markpizz** [comment]
To me, it seems somewhat wasteful to have some system(s) spend what seems like a ton of cycles doing all of the build work on every "push" to the repo.  Having BOTH GitHub and Travis do it would then be doubly so.  

If this is the new norm, then who am I to say it shouldn't be done.  Is there some way to limit these activities to at most 'n' times per some time interval?

**Comment by markpizz** [comment]
> I remember your concern about wasted cycles, which is why I set on: [pull_request] I don't know what it means exactly, but roughly that builds are only started when a pull request is opened. Commits pushed to regular branches will not be built.

That seems good for pull requests since they really don't come at a crazy pace.  However, Travis stuff seems to run every time I push one (or more) commits to the repo.  This inspires me to hold back some pushes, to avoid wasting cycles after a spelling error correction, but that then leaves the HEAD of the master branch on my local system ahead of GitHub and thus potentially staging sequencing issues with newly arriving pull requests...  I merely get to deal with it...

**Comment by markpizz** [comment]
How about we run with both GitHub Actions and Travis for a month and then take a measure of the advantage of GitHub Actions.  If it does well, then we retire the Travis stuff...

**Comment by larsbrinkhoff** [comment]
Yes, that sounds like a good plan.

**Pull request merged**
