### PR TITLE
AltairZ80: Fixed clang++ warnings in HAYES, M2SIO, and PMMI devices

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by markpizz** [comment]
Some of the additional compile warnings could be removed if:
```
Line 592 of s100_2sio.c
was:
    const char *fmt;
instead of:
    char *fmt;
```

**Comment by deltecent** [comment]
I don't get any additional compiler warnings. If there's some compiler switch I need to enable, that would helpful.

**Comment by markpizz** [comment]
```
make GCC=clang++ altairz80
```
on Linux 
on macOS I don't seem to get that error, but there certainly is no harm with the declaration of fmt to be 'const char *' I suggested.  All of your assignments of fmt assign it to a constant character string, right?

**Comment by deltecent** [comment]
>Some of the additional compile warnings could be removed...

That comment indicated there were multiple warnings. Is `fmt` at line 592 the only one?

**Comment by markpizz** [comment]
> That comment indicates there are multiple warnings. Is fmt at line 592 the only one?

Every assignment of fmt to a constant string produced a warning.  with const char * they all go away.

It looks OK now.

Meanwhile, Your changes weren't on the latest commit in the master branch when I checked this AM, so please pull before committing this stuff.

**Comment by markpizz** [comment]
There are other commits on the master branch that aren't included in your void branch.

I'll either cherry pick the changes and commit them with you as author, or preferably, you drop this PR and do a pull from the master branch before committing again.

**Comment by deltecent** [comment]
>I'll either cherry pick the changes and commit them...

I like that plan.

**Comment by larsbrinkhoff** [comment]
You can update an existing pull request by pushing to its branch, and completely rewrite it by force pushing.

I tried to jot down some hints for rewriting git branches:  
https://github.com/larsbrinkhoff/fearless-git

**Comment by markpizz** [comment]
Lars seems to do that all the time.

I just get the Pull Requests and don't generate them, so I'm not familiar with the more subtle means of working with them.

**Comment by deltecent** [comment]
>This branch has no conflicts with the base branch

I've never understood the need to have the very latest master changes in a pull request when there aren't any conflicts. Github doesn't know the difference as it is only looking at the deltas between the master branch and pull request. No other open source projects I participate with have this requirement.

**Comment by markpizz** [comment]
> That probably explains why it's a requirement here and nowhere else.

Nope.

The "requirement" is based on the fact that this repo has a relatively low commit rate, which can easily allow folks to follow the desired pull before commit pattern.  Otherwise, following your suggestion, I can either do more work and have to Cherry pick your commits and then have to remember to attribute the work to you (much more work for me), or I could merely "merge" your contribution(s) which would then clutter the commit history with merge commits, almost 1 for 1 for each of the external contributions.  A graphical representation of the commit history and the related branches then looks quite like spaghetti cluttered with all of these merge commits rather than a simple straight line history of the actual changes.

You just merged from the github.com/simh/simh master branch and produced a merge commit which, like I've said repeatedly I'm not interested in collecting.

**Comment by deltecent** [comment]
>I can either do more work and have to Cherry pick your commits

When I open a PR **there's only 1 commit** until you continually ask me to make more of them by incorporating other commits (which have nothing to with my commit) into my working branch. The PRs I submit shouldn't require any cherry picking at all. I, like you, am not a Git expert, so from my perspective, you are turning something simple that Git handles very well, into something unnecessarily complicated. So, yes, if you want these changes, cherry pick away through the massive amount of commits, provide command line examples of how to do this the Mark way, or delete the PR and someone else can submit the changes.

**Comment by markpizz** [comment]
Like I said previously, I don't do PRs, but if I were to guess (@larsbrinkhoff  please confirm or correct), the steps you'd need to do in this case are:

1) working the branch you've setup for this PR:
2) git reset --soft HEAD^
3) git pull https://github. com/song/simh master
4) commit your local changes which should be still sitting there
5) git push -f https://github. com/deltecent/simh

I'm pretty sure this is what @larsbrinkhoff does on a regular basis while a PR is pending and his stuff changes or something else in the master branch does.

The above mention of HEAD^ will probably need to be HEAD^^ to also remove the merge commit you recently created.

**Comment by larsbrinkhoff** [comment]
For the most common, uncomplicated case, I will do this whenever the master branch moves forward and I have a pending pull request:

1. git checkout branch
2. git fetch upstream
3. git rebase upstream/master

`branch` means the feature branch, i.e. the branch used to submit the pull request.  `upstream` is a "remote" I created for the official simh repository.  I go it like this:

git remote add upstream https://github.com/simh/simh

As for *why* I do it, it's the same reason Mark provided above.  I prefer a linear commit history without merge commits.  I didn't know this was a requirement for simh pull requests, it's just what I normally do.  Mark has an additional requirement that commit dates should also be monotonic.

**Comment by Rhialto** [comment]
There is this one thing I find annoying about the github workflow and pull requests(not specifically with simh, but I'll use it as an example). In order to make a pull request, you need to fork the original simh repository to your own simh version on github. Then you need to clone that to your local computer. There you create a branch, do your fixes, etc. You push that back to your simh on github, and you can create a pull request, which the upstream simh maintainer can accept.
So far so good.
But now you have a fork of simh on github, but it's out of date (because your nice pull request has been accepted). If you want to keep working and make some next improvement, there is nothing on github that helps you to keep your forked simh up to date.
You really have to go the circuitous route of adding the original simh as another remote to your local computer's simh. Then you must pull from from it, and push it back to your own github simh.
Github has nothing to make this easier. Gitlab at least has an automatic pulling mechanism to stay in sync. See for instance https://gitlab.com/Rhialto/k-9: "Mirrored from https://github.com/k9mail/k-9.git.  Pull mirroring updated 5 minutes ago. "

**Pull request closed without merging**
