### PR TITLE
3b2: Remove 3B2 simulator

### PR DESCRIPTION
**Pull request by sethm**

### CODE REVIEW

**Comment by markpizz** [comment]
I'll not be honoring simulator removal requests.  Sorry,

**Comment by rcornwell** [comment]
Please honor his and mine.

**Comment by markpizz** [comment]
It’s too bad that this license stuff goes both ways, isn’t it.

Please thank that fantastic guy Chris Hanson for inspiring this change in the simh universe.

I’m sorry to have been such a bother over the past 11 years to everyone I had interacted with.

Going forward, folks will still be able to freely access and use what’s in the existing repo under the “Closed Source” license terms specified.  I’ll probably address bug reports and maybe even pass them along to the respective simulator developers as appropriate.


  *   Mark

**Comment by sethm** [comment]
Mark, there is nobody to blame here but yourself. I will close this PR.

**Comment by rcornwell** [comment]
I will no longer accept bug reports that are submitted against simH tree.

And it would look good for you to honor request to remove files from the authors.

**Comment by markpizz** [comment]
On Tuesday, May 17, 2022 at 1:59 PM, Richard Cornwell wrote:
> I will no longer accept bug reports that are submitted against simH tree.

Any such reports will be passed along to you and you can do whatever you want
with the info.  Under the open source license this is lives under, I’ll be free to pick
up any changes you make in your sims repo from time to time unless you change
your license to a closed source one in order to lock me out.

> And it would look good for you to honor request to remove files from the authors.

I don’t do everything you ask me to, now matter how good it makes me look.

  *   Mark

**Comment by ams** [comment]
For anyone working or wanting to work on SIMH and doesn't want to let those changes back into this or any future hostile versions of SIMH, a suggestion is to licenses future changes under a copyleft license -- such changes cannot be merged back.

**Pull request closed without merging**
