### PR TITLE
ALTAIRZ80: Added support for "SET CPU HISTORY" and "SHOW CPU HISTORY"

### PR DESCRIPTION
**Pull request by deltecent**
Fixed issues reported by Peter and Mark.

Reference #838

### CODE REVIEW

**Comment by markpizz** [comment]
Patrick,

Given the low commit rate on this repo, I like to keep a single commit line without merge commits.  To achieve this, we strive to get everyone to do a pull from the master branch before the commit in their pull request.  Please do that, or you don't want to be recorded as the committer of your changes, I'll cherry pick your changes and attribute you as the author and commit it myself.

- Mark

**Comment by psco** [comment]
I think the "t_value op[3];" and related read/write needs to be "t_value op[4];" as the Z80 also has 4-byte instructions. Otherwise the symbolic disassembler will access incorrect memory locations when disassembling 4-byte instructions.

**Comment by deltecent** [comment]
I will make that change. I don’t know anything about the Z80. I should probably download a data sheet.

**Comment by deltecent** [comment]
I remember being scolded on this before. No problem.

**Comment by markpizz** [comment]
Hold off for a bit I'm pushing out other commits.

**Comment by markpizz** [comment]
Good to go now.

**Comment by deltecent** [comment]
I merged with master and now I'm getting the following warnings:

./sim_disk.c:2740:94: warning: unknown escape sequence '\.' [-Wunknown-escape-sequence]
                sim_messagef (SCPE_OK, "%s: No File System found on '%s', skipping autosizing\.n", sim_uname (uptr), cptr);
                                                                                             ^~
./sim_disk.c:5566:26: warning: incompatible pointer types passing 'uint32 *' (aka 'unsigned int *') to parameter of type 'size_t *' (aka 'unsigned long *')
      [-Wincompatible-pointer-types]
                         BytesRead,
                         ^~~~~~~~~
./sim_disk.c:4403:79: note: passing argument to parameter 'bytesread' here
static t_stat ReadFilePosition(FILE *File, void *buf, size_t bufsize, size_t *bytesread, uint64 position)
                                                                              ^
./sim_disk.c:5601:30: warning: incompatible pointer types passing 'uint32 *' (aka 'unsigned int *') to parameter of type 'size_t *' (aka 'unsigned long *')
      [-Wincompatible-pointer-types]
                             &BytesThisRead,
                             ^~~~~~~~~~~~~~
./sim_disk.c:4403:79: note: passing argument to parameter 'bytesread' here
static t_stat ReadFilePosition(FILE *File, void *buf, size_t bufsize, size_t *bytesread, uint64 position)
                                                                              ^
./sim_disk.c:5690:27: warning: incompatible pointer types passing 'uint32 *' (aka 'unsigned int *') to parameter of type 'size_t *' (aka 'unsigned long *')
      [-Wincompatible-pointer-types]
                          BytesWritten,
                          ^~~~~~~~~~~~
./sim_disk.c:4419:80: note: passing argument to parameter 'byteswritten' here
static t_stat WriteFilePosition(FILE *File, void *buf, size_t bufsize, size_t *byteswritten, uint64 position)
                                                                               ^
./sim_disk.c:5833:31: warning: incompatible pointer types passing 'uint32 *' (aka 'unsigned int *') to parameter of type 'size_t *' (aka 'unsigned long *')
      [-Wincompatible-pointer-types]
                              &BytesThisWrite,
                              ^~~~~~~~~~~~~~~
./sim_disk.c:4419:80: note: passing argument to parameter 'byteswritten' here
static t_stat WriteFilePosition(FILE *File, void *buf, size_t bufsize, size_t *byteswritten, uint64 position)

**Pull request closed without merging**
