### PR TITLE
BESM6: Corrected responsiveness of the TTY I/O initiation;

### PR DESCRIPTION
**Pull request by leobru**
implemented switching between turbo and "authentic feel" mode of TTY I/O
with varying Baud rate.

### CODE REVIEW

**Comment by markpizz** [comment]
Leo,

I hate to be a stickler, but:

1) The pattern for commit messages is:
COMPONENT/SIMULATOR: one line summary max at 80 columns
<blank-line>
<extra descriptive information for as many lines shorter than 80 as 
  is interesting or necessary - Maybe no extra descriptive commentary
  if the summary is sufficient>

2) It seems that tab characters have crept into your recent edits to 
besm6_tty.c.  Project standards are that tabs get expanded to spaces
in source and/or other text files and these files have CRLF line endings.
Your line endings are good and the only tabs are the recent changes to
besm6_tty.c.

**Comment by leobru** [comment]
What are my choices, apart from removing the project and cloning again?

**Comment by markpizz** [comment]
Since github.com/leobru/simh merely exists publicly for you to pass stuff to me (and no one else is referencing it), rewriting history is OK since I know it is about to happen.

You can rewrite history in your repo either as you suggest, or what I think would be equivalent might be:

    $ git reset --soft HEAD^
    $ git push -f 

make your changes and do a new commit followed by another push with a new pull request.

**Comment by markpizz** [comment]
Note.  I just realized that if you're using the github web interface all of my comments were not visible due to markdown misinterpreting my \< and \> characters.  Please read the details before your next commit.

**Comment by larsbrinkhoff** [comment]
If you add a file `CONTRIBUTING.md` to the toplevel directory, there will be a suggestion to read it when people make a pull request.  It should contain guidelines for how to submit contributions.

**Comment by markpizz** [comment]
Thanks for the suggestion.  I've actually got a draft of such a document in progress.

**Pull request closed without merging**
