### PR TITLE
Install prerequisite libraries for Travis CI.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This install some prerequisite  libraries for the Travis CI build.

For an unknown reason I had to install libegl1-mesa-dev and libgles2-mesa-dev too to make apt happy.

### CODE REVIEW

**Comment by markpizz** [comment]
How about locating the deps.sh script in a .travis directory?
It would be nice if the .travis.yml could be there as well (like the .github directory).  Oh well.

**Comment by larsbrinkhoff** [comment]
Sure, I moved it.  I don't think the yml file can be moved though.

**Comment by markpizz** [comment]
Also, please add libsdl2-ttf-dev to the Linux package set.  No such package is yet available for HomeBrew on OS X.

**Comment by larsbrinkhoff** [comment]
Done.

**Pull request merged**
