### PR TITLE
ALTAIRZ80: Adds TARBELL device for Tarbell SSSD Disk Controller

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by markpizz** [comment]
A Couple of comments:
1) routines that interface with a SCP command (link ATTACH, or SET and SHOW) should emit error messages by calling sim_messagef().
2) The comment block at the top of the new source code module (s100_tarbell.c) should have something that looks a lot like what is in all the other simh source code modules.  Look at altairz80_cpu.c for an starting point.
3) I notice that you're including windows.h when _WIN32 is defined.  This certainly doesn't belong here, but I now see that you did this since it was done in many of the other modules in this simulator.  This include will be removed from the rest of the AltairZ80, but you should remove it from your module.

**Comment by markpizz** [comment]
Additionally, the compile of this module fails on Windows under Visual Studio.  The following errors are produced.  On the fly loop variable declarations are some of these.  The others are due to passing a uint16 track and sector values to parameters which are only uint8.

```
1>Compiling...
1>s100_tarbell.c
1>..\AltairZ80\s100_tarbell.c(318) : error C2143: syntax error : missing ';' before 'type'
1>..\AltairZ80\s100_tarbell.c(318) : error C2143: syntax error : missing ';' before 'type'
1>..\AltairZ80\s100_tarbell.c(318) : error C2143: syntax error : missing ')' before 'type'
1>..\AltairZ80\s100_tarbell.c(318) : error C2143: syntax error : missing ';' before 'type'
1>..\AltairZ80\s100_tarbell.c(318) : warning C4552: '<' : operator has no effect; expected operator with side-effect
1>..\AltairZ80\s100_tarbell.c(318) : error C2059: syntax error : ')'
1>..\AltairZ80\s100_tarbell.c(318) : error C2143: syntax error : missing ';' before '{'
1>..\AltairZ80\s100_tarbell.c(628) : warning C4028: formal parameter 2 different from declaration
1>..\AltairZ80\s100_tarbell.c(770) : warning C4244: 'function' : conversion from 'uint16' to 'uint8', possible loss of data
1>..\AltairZ80\s100_tarbell.c(770) : warning C4244: 'function' : conversion from 'uint16' to 'uint8', possible loss of data
1>..\AltairZ80\s100_tarbell.c(795) : warning C4244: 'function' : conversion from 'uint16' to 'uint8', possible loss of data
1>..\AltairZ80\s100_tarbell.c(795) : warning C4244: 'function' : conversion from 'uint16' to 'uint8', possible loss of data
```

**Comment by markpizz** [comment]
Making progress.

Meanwhile, windows still sees:
```
2>s100_tarbell.c
2>..\AltairZ80\s100_tarbell.c(557) : warning C4101: 'rtn' : unreferenced local variable
2>..\AltairZ80\s100_tarbell.c(554) : warning C4101: 'driveNum' : unreferenced local variable
2>..\AltairZ80\s100_tarbell.c(637) : warning C4028: formal parameter 2 different from declaration
2>..\AltairZ80\s100_tarbell.c(639) : warning C4101: 'driveNum' : unreferenced local variable
```

Additionally, you should read through the comment block at the top of the s100_tarbell.c file and change Peter Schorn's name to yours...  :-)

**Comment by markpizz** [comment]
This message:
```
2>..\AltairZ80\s100_tarbell.c(637) : warning C4028: formal parameter 2 different from declaration
```
got me to look closely at the declaration of this routine as well as others in this module.

It is somewhat unusual for me to see parameters to routines that are passed by value to be explicitly declared as const:
```
static uint8 TARBELL_Write(const uint32 Addr, const int32 Data)
```

I guess that this would hopefully get the compiler to complain about any attempt within that routine to change the value of these parameters, but I'm not sure that really does much...

**Comment by deltecent** [comment]
I think you're right about the ```const``` declarations. I removed them.

I don't have a Windows compiler, but I enabled ```-Wall``` for ```gcc```. Hopefully Windows doesn't find any more problems.

**Comment by markpizz** [comment]
No more Windows problems now.  I'm waiting for Peter Schorn's review of this since he maintains/owns this simulator.  He's been traveling, and said he'd get to it tomorrow.

**Comment by deltecent** [comment]
That sounds great. I appreciate all of the help. Mike Douglas has run it through some tests without any problems. I do want to improve the documentation on how the Tarbell controller and FD1771 actually work, and I still need to implement the read track function, but I have to write a program to test that first since that function doesn't seem to be used by CP/M. I'll push a PR when I have those ready for review.

**Pull request merged**
