### PR TITLE
BESM6: Corrected handling of disk device groups.

### PR DESCRIPTION
**Pull request by leobru**
Device groups now work, up to 64 disk drives may be used.

### CODE REVIEW

**Comment by markpizz** [comment]
Leo,

Please hold off on this PR.

Don’t cancel it, just wait a day or so.  I’m trying to get the logic correct to avoid that step in the CI/CD activities.

When I’ve got it straight, I’ll suggest the simplest way to get this in with you as both the author and committer.

Sorry for the confusion.

Mark

**Comment by markpizz** [comment]
Things are ready now.

You should be able to move forward with this with the following commands:

    $ # back out your BESM6 commit, but leave your changed file in the working directory:
    $ git reset --soft HEAD^
    $ # pickup the latest master branch state from https://github.com/simh/simh
    $ git pull https://github.com/simh/simh
    $ # commit your change, on your commit message,  Please leave a blank 
    $ # line between the "BESM6: Corrected handling of disk device groups." 
    $ # and the  "Device groups now work, up to 64 disk drives may be used."
    $ git commit
    $ # Update the PR to reflect your change (using the -f flag to force your 
    $ # current local repo state to replace the prior PR repo contents).
    $ git push -f

This will kick off the CI/CD to verify clean builds on Linux, macOS and Windows.

Alternatively, if you are OK with me doing the commit with designated as the author, I can do that.

**Comment by leobru** [comment]
Mark,

I'm OK with you doing the commit. Please go ahead.

Thank you,
Leo

**Comment by markpizz** [comment]
Merged.  Thanks.

**Pull request closed without merging**
