### PR TITLE
Add Imlac simulator

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I will turn this into a pull request when the Imlac simulator is ready for merging.

For now, there are some things that need fixing:

- [x] Crash after a minute or so.
- [x] Not possible to interrupt with Control-E.
- [x] Configuration for bootstrap ROM.
- [x] Line drawing algorithm needs polish.
- [x] Check that keyboard input is fully working.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm making this a *"work in progress"* pull request with the intent that this could go in soon, but with the caveat that there are some problems to be fixed first.

**Comment by markpizz** [comment]
Sorry I haven't had a chance to dig deeply into this problem.  I'm too busy.

In any case, I just committed a change which may improve things for this situation.  Please give the latest code a try.

**Comment by larsbrinkhoff** [comment]
No problem.  I'm trying to chip away at the problem on my end.

I'm running the Imlac simulator on my Linux laptop as well as on a Raspberry Pi 3.  On the Pi it dies very quickly.  I have confirmed memory over consumption is the problem, because the "out-of-memory killer" is invoked to remove a process and it selects the imlac process to go.  I have determined that the call to `display_age` triggers the crash; without this call the simulator runs fine.

I tried your latest updates, and they don't solve the problem but it's probably an improvement.  The simulator now dies from a segmentation fault in `vid_draw`, line 724 in sim_video.c.  The backtrace is:

```
#0  0x00000000004853cb in vid_draw (x=0, y=0, w=1024, h=1024, 
    buf=0x7fffef986010) at ./sim_video.c:724
#1  0x000000000040ce9e in ws_sync () at ./display/sim_ws.c:477
#2  0x000000000040b79f in display_sync () at ./display/display.c:1025
#3  0x000000000040aa9d in display_age (t=1, slowdown=0)
    at ./display/display.c:658
#4  0x000000000040cfb8 in imlac_cycle (us=100, slowdown=0)
    at ./display/imlac.c:47
#5  0x0000000000409392 in crt_svc (uptr=0x6c0f40 <crt_unit>)
    at ./imlac/imlac_crt.c:60
#6  0x000000000042a2f5 in sim_process_event () at ./scp.c:11325
#7  0x0000000000407b16 in sim_instr () at ./imlac/imlac_cpu.c:419
#8  0x0000000000423157 in run_cmd (flag=1, cptr=0x7fffffff0202 "")
    at ./scp.c:8532
#9  0x0000000000412d92 in do_cmd_label (flag=0, 
    fcptr=0x7fffffff96b0 "ssv22.simh", label=0x0) at ./scp.c:3911
#10 0x0000000000412059 in do_cmd (flag=0, fcptr=0x7fffffff96b0 "ssv22.simh")
    at ./scp.c:3735
#11 0x000000000040e119 in main (argc=2, argv=0x77b040) at ./scp.c:2834
```

Line 724 is this: `(vid_dst_last->x == x) && (vid_dst_last->y == y) && /* AND identical position? */`.  `vid_dst_last` is 0 at this point.  It shouldn't be referenced because it's first checked against 0, but according to my debugger it is.  I'll examine this further.

**Comment by larsbrinkhoff** [comment]
Your update also affects the PDP-11 simulator the same way.  Steps to reproduce:

1. Build `pdp11` with `DEBUG=1`.
2. Start `pdp11`.
3. `set daz enabled`
4. `boot daz`
5. Wait 1-5 minutes.
6. Crash in `vid_draw`.

I believe I had this running for hours before.

**Comment by markpizz** [comment]
Hmmm... All accesses to the prior draw state weren't protected by the mutex.  They now are.

**Comment by larsbrinkhoff** [comment]
Thank you, that does seem to fix the problem.

**Comment by markpizz** [comment]
Just the new segfault, and memory blow up problem, right?

Are there still other issues?

**Comment by larsbrinkhoff** [comment]
Yes, segfault and memory problems no longer appear.

I can't seem to type ^E or ^F or whatever's supposed to break out to the sim> prompt.  That's the only major outstanding issue.  It used to work but stopped at some point along the when when I added more features.  I'll look into it tomorrow.

**Comment by markpizz** [comment]
Clock test works for me on Windows, including ^E.

Another update to the video code moving the gamecontroller/joystick initialization/cleanup to a more appropriate place so that it doesn't shutdown while some events may be pending.

**Comment by larsbrinkhoff** [comment]
Looks like I need to call sim_poll_kbd for ^E to work.  (I have a vague memory this worked without sim_poll_kbd before I implemented imlac_kbd.c, but never mind.)

With that fixed, I declare this "ready for review".

**Comment by markpizz** [comment]
> Looks like I need to call sim_poll_kbd for ^E to work. (I have a vague memory this worked without sim_poll_kbd before I implemented imlac_kbd.c, but never mind.)

There was a bug that disabled auto detecting WRU if sim_video was in use on Linux.  That has been fixed now.  You no longer need to be calling sim_poll_kbd().

Otherwise:
1) imlac_kbd.c has tabs in it.
2) Correct line endings to CRLF
3) Squash these commits
4) Use a current commit date rather than a couple of months back

FYI.  There is a new sim_video which properly initializes (and cleans up) the newly added draw mutex and gamepad/joystick initialization on different host setups.

**Comment by markpizz** [comment]
Build fails without libSDL2.

Please fix:
```
*** Info ***
*** Info *** The simulator you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the development components of libSDL2 packaged for
*** Info *** your operating system distribution for your Linux
*** Info *** system:
*** Info ***        $ sudo apt-get install libsdl2-dev libpng-dev
*** Info ***
***
*** imlac Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 9.3.0.
*** - Per simulator tests will be run.
***
*** git commit id is 9a760126d66ca2a3818faf52b0b3421a5d1c8ad6.
*** git commit time is 2020-06-11T13:22:37-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -DSIM_GIT_COMMIT_ID=9a760126d66ca2a3818faf52b0b3421a5d1c8ad6 -DSIM_GIT_COMMIT_TIME=2020-06-11T13:22:37-0700  -DSIM_COMPILER="GCC Version: 9.3.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./imlac/imlac_sys.c ./imlac/imlac_cpu.c ./imlac/imlac_dp.c ./imlac/imlac_crt.c ./imlac/imlac_kbd.c ./imlac/imlac_tty.c ./imlac/imlac_pt.c   ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./imlac  -o BIN/imlac -lm -lrt -lpthread -lpcre -ldl -lpng -lz
/usr/bin/ld: /tmp/ccTAgHh4.o: in function `crt_svc':
imlac_crt.c:(.text+0x10): undefined reference to `imlac_cycle'
/usr/bin/ld: /tmp/ccTAgHh4.o: in function `crt_reset':
imlac_crt.c:(.text+0x3f): undefined reference to `display_close'
/usr/bin/ld: imlac_crt.c:(.text+0x59): undefined reference to `display_reset'
/usr/bin/ld: imlac_crt.c:(.text+0x66): undefined reference to `imlac_init'
/usr/bin/ld: /tmp/ccTAgHh4.o: in function `crt_point':
imlac_crt.c:(.text+0xf9): undefined reference to `imlac_point'
/usr/bin/ld: /tmp/ccTAgHh4.o: in function `crt_line':
imlac_crt.c:(.text+0x1a6): undefined reference to `imlac_line'
/usr/bin/ld: /tmp/cclBkOC3.o: in function `kbd_reset':
imlac_kbd.c:(.text+0x379): undefined reference to `vid_display_kb_event_process'
/usr/bin/ld: imlac_kbd.c:(.text+0x3bd): undefined reference to `vid_display_kb_event_process'
/usr/bin/ld: /tmp/cclBkOC3.o: in function `kbd_event':
imlac_kbd.c:(.text+0x44c): undefined reference to `vid_key_name'
collect2: error: ld returned 1 exit status
make: *** [makefile:2223: BIN/imlac] Error 1
```

**Comment by larsbrinkhoff** [comment]
Thanks.  I believe your comments have been adresses:

0. No longer using sim_poll_kbd for ^E.
1. Expanded tabs.
2. Fixed line endings.
3. There is only one commit, so nothing to squash.
4. Date is now Fri Jun 12 16:05:50 2020 +0200.
5. Added #ifdef HAVE_LIBSDL where necessary.

**Pull request merged**
