### PR TITLE
AltairZ80: vfdhd: Fix unit detach.

### PR DESCRIPTION
**Pull request by hharte**
FYI, @psco

### CODE REVIEW

**Comment by psco** [comment]
Looks good

**Comment by markpizz** [comment]
Actually.  It could be improved since there are now return statements in a row (lines 340 & 342).  Only the first will be effective and the second will be  dead code...

**Comment by psco** [comment]
You're absolutely right. And while we are at it, one could remove the variable `r` altogether and have
    `return detach_unit(uptr);  /* detach unit */`
as the last statement of `vfdhd_detach`.

**Comment by hharte** [comment]
Thanks for the feedback, updated.

**Pull request merged**
